### ISSUE TITLE
Seed number display - in 'Check if Generate works' section of the code

### ISSUE THREAD

**Issue by illustrationlibrary** [sugyan/stable-diffusion-morphing#1]
I think if you could include a seed= in 'Check if Generate works', or even if the seed could be included in the generated image's file name, it would really help specify what the users uses as seed in the morphing section of the code. 

ie, the test area would be where seeds and ideas are generated, then the user would feed the prompts and seeds generated into the morph section, knowing more or less what they would be getting back from the result.

**Comment by sugyan** [comment]
I updated my notebook. Thank you for your advice!
